package org.example.Domain.Util;

/**
 * Códigos de erro de validação e processamento
 */
public enum Erro {
    CPF_INVALIDO,
    NOME_INVALIDO,
    DATA_INVALIDA,
    CLIENTE_MENOR_DE_IDADE,
    CPF_JA_EXISTENTE,
    LOGRADOURO_INVALIDO,
    NUMERO_INVALIDO,
    COMPLEMENTO_INVALIDO,
    BAIRRO_INVALIDO,
    CIDADE_INVALIDA,
    CEP_INVALIDO,
    UF_INVALIDA,
    DDD_INVALIDO,
    NUMERO_TEL_INVALIDO,
    ENDERECO_INVALIDO,
    TELEFONE_INVALIDO,
    ERRO_BD,
    PLACA_INVALIDA,
    PLACA_JA_EXISTENTE,
    MODELO_INVALIDO,
    ANO_INVALIDO,
    DIARIA_INVALIDA,
    QUILOMETRAGEM_INVALIDA,
    LOCACAO_JA_EXISTENTE
}
